parameters:
#  database_host: 127.0.0.1
  database_host: localhost
  database_port: 3306
  database_name: testdb
  database_user: user
  database_password: 123123
  mailer_transport: smtp
#  mailer_host: 127.0.0.1
#  mailer_user: null
#  mailer_password: null
  secret: 037ab82c601c10402408b2b190d5530d602b5809

  doctrine:
    dbal:
    driver:   pdo_mysql
    host:     '%database_host%'
    dbname:   '%database_name%'
    user:     '%database_user%'
    password: '%database_password%'
    charset: utf8mb4
